[package]
name = "blog-rs"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = "fat"
opt-level = "z"
strip = true
panic = "abort"

[dependencies]
tiny_http = "0.12"
maud = "0.26"
comrak = "0.28"
time = {version = "0.3", features = ["formatting", "parsing"]}
